# Generated by Django 5.1.12 on 2025-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('epost', models.EmailField(max_length=254, unique=True)),
                ('posisjon', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
