# Generated by Django 5.1.12 on 2025-09-18 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansatte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ansatt',
            name='epost',
        ),
        migrations.RemoveField(
            model_name='ansatt',
            name='navn',
        ),
        migrations.RemoveField(
            model_name='ansatt',
            name='posisjon',
        ),
        migrations.AddField(
            model_name='ansatt',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='ansatt_dato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='kjonn',
            field=models.CharField(blank=True, choices=[('M', 'Mann'), ('K', 'Kvinne'), ('A', 'Annet')], max_length=10),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='personnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='telefon',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ansatt',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ansatt',
            name='roller',
            field=models.ManyToManyField(blank=True, to='ansatte.role'),
        ),
    ]
