# Generated by Django 5.1.12 on 2025-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansatte', '0002_role_remove_ansatt_epost_remove_ansatt_navn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100, unique=True)),
                ('beskrivelse', models.TextField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('opprettet_dato', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='ansatt',
            name='roller',
            field=models.ManyToManyField(blank=True, to='ansatte.rolle'),
        ),
    ]
