# Generated by Django 5.1.12 on 2025-09-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('epost', models.EmailField(blank=True, max_length=254)),
                ('organisasjonsnummer', models.CharField(blank=True, max_length=20)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
